#!/usr/bin/env python3
"""EHW-0.4: compare evolved INT8 weights against the M7.5.3 trained tile."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from types import SimpleNamespace

import oracle_evolve as evo


DEFAULT_DOC = Path("docs/ehw0_4_results.md")
DEFAULT_CSV = Path("runs/ehw0_4_compare.csv")


def genome_str(genome: list[int]) -> str:
    return " ".join(str(v) for v in genome)


def hamming(a: list[int], b: list[int]) -> int:
    return sum(int(x != y) for x, y in zip(a, b))


def first_converged_generation(csv_path: Path, target_correct: int) -> int | None:
    with csv_path.open(newline="") as f:
        for row in csv.DictReader(f):
            if int(row["best_correct"]) >= target_correct:
                return int(row["gen"])
    return None


def run_ga(seed: int, population: int, generations: int, csv_path: Path) -> tuple[list[int], evo.Score, int | None]:
    args = SimpleNamespace(
        seed=seed,
        rng="xorshift",
        population=population,
        generations=generations,
        target_correct=40,
        init_span=32,
        elites=2,
        tournament=3,
        crossover_rate=0.70,
        mutation_rate=0.03,
        mutation_step=8,
        report_every=10,
        csv=str(csv_path),
        verbose=False,
    )
    best, score = evo.run_ga(args)
    return best, score, first_converged_generation(csv_path, args.target_correct)


def row(name: str, source: str, genome: list[int], score: evo.Score, convergence: str) -> dict[str, str]:
    preds = evo.predictions(genome)
    return {
        "name": name,
        "source": source,
        "convergence": convergence,
        "label_correct": f"{score.correct}/{evo.NTEST}",
        "label_acc": f"{score.accuracy:.3f}",
        "sse": str(score.sse),
        "fitness": str(score.fitness),
        "golden_mismatches": str(evo.golden_mismatches(genome)),
        "pred_bitmap": "".join(str(v) for v in preds),
        "genome": genome_str(genome),
    }


def markdown_table(rows: list[dict[str, str]]) -> str:
    cols = ["Weights", "Method", "Convergence", "Label Acc", "SSE", "Fitness", "M7.5.3 Golden Mismatches"]
    lines = [
        "| " + " | ".join(cols) + " |",
        "|---|---|---|---:|---:|---:|---:|",
    ]
    for r in rows:
        lines.append(
            "| {name} | {source} | {convergence} | {label_correct} ({label_acc}) | {sse} | {fitness} | {golden_mismatches} |".format(**r)
        )
    return "\n".join(lines)


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def write_doc(path: Path, rows: list[dict[str, str]], ga_genome: list[int], trained_genome: list[int],
              seed: int, population: int, generations: int, ga_csv: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    ga = rows[0]
    trained = rows[1]
    diff = hamming(ga_genome, trained_genome)
    doc = f"""# EHW-0.4 Results — Evolution vs Gradient Training

Generated by:

```bash
python3 sim/ehw0_4_compare.py --seed {seed} --population {population} --generations {generations}
```

Both rows use the same M7.5.3-lite fixed-point 4-4-2 net and the same 40 held-out
2x2 MNIST 0/1 samples. The only difference is how the 24 INT8 weights are chosen.

{markdown_table(rows)}

## Interpretation

- The board-verified GA run reaches `{ga['label_correct']}` label accuracy at
  `{ga['convergence']}` with SSE `{ga['sse']}`.
- The M7.5.3 trained tile reproduces its upstream golden bitmap exactly
  (`{trained['golden_mismatches']}` golden mismatches), but that golden bitmap is
  `{trained['label_correct']}` against labels on this test set.
- The evolved INT8 genome is therefore better on this quantized deployment metric:
  it finds a `{ga['label_correct']}` solution directly in the hardware-visible
  INT8 search space, while the gradient-trained Q8.8 master quantizes to a
  `{trained['label_correct']}` INT8 tile.
- The two 24-byte genomes differ in `{diff}` positions, so the GA is not merely
  preserving the M7.5.3 trained tile.

## Genomes

GA champion:

```text
{ga['genome']}
```

M7.5.3 trained tile:

```text
{trained['genome']}
```

## Reproducibility

- GA curve CSV: `{ga_csv}`
- Comparison CSV: `runs/ehw0_4_compare.csv`
- RNG: xorshift32, seed `{seed}`
- Population: `{population}`
- Generation cap: `{generations}`
- Fitness: `1_000_000 * label_correct - SSE`
"""
    path.write_text(doc)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=3)
    ap.add_argument("--population", type=int, default=32)
    ap.add_argument("--generations", type=int, default=64)
    ap.add_argument("--doc", type=Path, default=DEFAULT_DOC)
    ap.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    ap.add_argument("--ga-csv", type=Path, default=Path("runs/ehw0_4_ga_curve.csv"))
    args = ap.parse_args()

    ga_genome, ga_score, gen = run_ga(args.seed, args.population, args.generations, args.ga_csv)
    trained_genome = evo.M753_TRAINED_GENOME[:]
    trained_score = evo.evaluate(trained_genome)

    convergence = f"generation {gen}" if gen is not None else f">{args.generations} generations"
    rows = [
        row("EHW GA champion", "fitness-driven INT8 evolution", ga_genome, ga_score, convergence),
        row("M7.5.3 trained tile", "gradient-trained Q8.8 master quantized to INT8", trained_genome, trained_score, "60 epochs"),
    ]
    write_csv(args.csv, rows)
    write_doc(args.doc, rows, ga_genome, trained_genome, args.seed, args.population, args.generations, args.ga_csv)

    print(markdown_table(rows))
    print(f"\nwrote {args.doc}")
    print(f"wrote {args.csv}")
    return 0 if ga_score.correct == 40 and trained_score.correct == 37 and evo.golden_mismatches(trained_genome) == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
